### ISSUE TITLE
Polygon extraction module not found

### ISSUE THREAD

**Issue by Alexchen88888** [ste-fa-no-z/projectRegularization#1]
Hi everyone,
many thanks to @ste-fa-no-z for the awesome implementations.
I have a question for this repo.
I did not find Polygon extraction module in this repo.
where I could find this?
Looking forward your reply

**Comment by zorzi-s** [comment]
Hi @Alexchen88888,
my apologies for the late reply. 
The polygonization step is not yet public available. I hope to release it soon!
